project_id = "navlxvufcajsozhvbulu"

[functions.wallet-cron]
verify_jwt = false

[functions.sepay-webhook]
verify_jwt = false

[functions.casso-webhook]
verify_jwt = false

[functions.release-pi-early]
verify_jwt = true

[functions.backfill-wallet-data]
verify_jwt = true

[functions.calculate-product-scores]
verify_jwt = false

[functions.product-scores-cron]
verify_jwt = false

[functions.create-service-ticket]
verify_jwt = true

[functions.send-service-quote]
verify_jwt = true

[functions.accept-service-quote]
verify_jwt = true

[functions.complete-service-ticket]
verify_jwt = true
